# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 */24 * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: env
    permissions:
      contents: write
    steps:
    - uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        committer_token: ${{ secrets.GITHUB_TOKEN }}

        # Options.
        user: JajoScript
        template: classic
        base: header, activity, community, repositories, metadata
        config_animations: yes
        config_timezone: America/Santiago
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
        plugin_languages: yes
        plugin_languages_colors: github
